/**
 * The countries Last.fm's geo charts can be asked for.
 *
 * `geo.getTopTracks` takes a country *name*, but its accepted spellings are
 * Last.fm's own and differ from the station directory's: "United States",
 * not "The United States Of America"; "Korea, Republic of", not "South
 * Korea"; "Turkey", not "Türkiye". Feeding RadioBrowser's names straight
 * through made Last.fm answer "country param invalid" for a good third of
 * them, and the picker went through RadioBrowser, so it was also empty
 * whenever that directory happened to be down.
 *
 * So the list is bundled instead of borrowed. `value` is the exact string
 * Last.fm accepts (probed against the live API), `name` is what the picker
 * shows, and `code` is the ISO 3166-1 alpha-2 code — the one thing both
 * directories agree on, and what lets the recently picked countries stay
 * shared with the radio station directory (services/recentCountries.ts).
 *
 * `name` and `value` are separate because Last.fm's own spelling is not
 * always the friendlier one: the API still wants "Libyan Arab Jamahiriya"
 * and "Swaziland", but nobody would look for Libya or Eswatini under those.
 */
export interface LastfmCountry {
  code: string
  name: string
  value: string
}

export const LASTFM_COUNTRIES: LastfmCountry[] = [
  { code: 'AF', name: 'Afghanistan', value: 'Afghanistan' },
  { code: 'AL', name: 'Albania', value: 'Albania' },
  { code: 'DZ', name: 'Algeria', value: 'Algeria' },
  { code: 'AS', name: 'American Samoa', value: 'American Samoa' },
  { code: 'AD', name: 'Andorra', value: 'Andorra' },
  { code: 'AO', name: 'Angola', value: 'Angola' },
  { code: 'AI', name: 'Anguilla', value: 'Anguilla' },
  { code: 'AQ', name: 'Antarctica', value: 'Antarctica' },
  { code: 'AG', name: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina', value: 'Argentina' },
  { code: 'AM', name: 'Armenia', value: 'Armenia' },
  { code: 'AW', name: 'Aruba', value: 'Aruba' },
  { code: 'AU', name: 'Australia', value: 'Australia' },
  { code: 'AT', name: 'Austria', value: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan', value: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas', value: 'Bahamas' },
  { code: 'BH', name: 'Bahrain', value: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh', value: 'Bangladesh' },
  { code: 'BB', name: 'Barbados', value: 'Barbados' },
  { code: 'BY', name: 'Belarus', value: 'Belarus' },
  { code: 'BE', name: 'Belgium', value: 'Belgium' },
  { code: 'BZ', name: 'Belize', value: 'Belize' },
  { code: 'BJ', name: 'Benin', value: 'Benin' },
  { code: 'BM', name: 'Bermuda', value: 'Bermuda' },
  { code: 'BT', name: 'Bhutan', value: 'Bhutan' },
  { code: 'BO', name: 'Bolivia', value: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana', value: 'Botswana' },
  { code: 'BV', name: 'Bouvet Island', value: 'Bouvet Island' },
  { code: 'BR', name: 'Brazil', value: 'Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory', value: 'British Indian Ocean Territory' },
  { code: 'VG', name: 'British Virgin Islands', value: 'Virgin Islands, British' },
  { code: 'BN', name: 'Brunei Darussalam', value: 'Brunei Darussalam' },
  { code: 'BG', name: 'Bulgaria', value: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso', value: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi', value: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde', value: 'Cape Verde' },
  { code: 'KH', name: 'Cambodia', value: 'Cambodia' },
  { code: 'CM', name: 'Cameroon', value: 'Cameroon' },
  { code: 'CA', name: 'Canada', value: 'Canada' },
  { code: 'KY', name: 'Cayman Islands', value: 'Cayman Islands' },
  { code: 'CF', name: 'Central African Republic', value: 'Central African Republic' },
  { code: 'TD', name: 'Chad', value: 'Chad' },
  { code: 'CL', name: 'Chile', value: 'Chile' },
  { code: 'CN', name: 'China', value: 'China' },
  { code: 'CX', name: 'Christmas Island', value: 'Christmas Island' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', value: 'Cocos (Keeling) Islands' },
  { code: 'CO', name: 'Colombia', value: 'Colombia' },
  { code: 'KM', name: 'Comoros', value: 'Comoros' },
  { code: 'CG', name: 'Congo', value: 'Congo' },
  { code: 'CK', name: 'Cook Islands', value: 'Cook Islands' },
  { code: 'CR', name: 'Costa Rica', value: 'Costa Rica' },
  { code: 'HR', name: 'Croatia', value: 'Croatia' },
  { code: 'CU', name: 'Cuba', value: 'Cuba' },
  { code: 'CW', name: 'Curaçao', value: 'Curaçao' },
  { code: 'CY', name: 'Cyprus', value: 'Cyprus' },
  { code: 'CZ', name: 'Czechia', value: 'Czech Republic' },
  { code: 'CI', name: "Côte d'Ivoire", value: "Cote d'Ivoire" },
  {
    code: 'CD',
    name: 'Democratic Republic of the Congo',
    value: 'Congo, The Democratic Republic of the',
  },
  { code: 'DK', name: 'Denmark', value: 'Denmark' },
  { code: 'DJ', name: 'Djibouti', value: 'Djibouti' },
  { code: 'DM', name: 'Dominica', value: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic', value: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador', value: 'Ecuador' },
  { code: 'EG', name: 'Egypt', value: 'Egypt' },
  { code: 'SV', name: 'El Salvador', value: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea', value: 'Eritrea' },
  { code: 'EE', name: 'Estonia', value: 'Estonia' },
  { code: 'SZ', name: 'Eswatini', value: 'Swaziland' },
  { code: 'ET', name: 'Ethiopia', value: 'Ethiopia' },
  { code: 'FK', name: 'Falkland Islands', value: 'Falkland Islands (Malvinas)' },
  { code: 'FO', name: 'Faroe Islands', value: 'Faroe Islands' },
  { code: 'FJ', name: 'Fiji', value: 'Fiji' },
  { code: 'FI', name: 'Finland', value: 'Finland' },
  { code: 'FR', name: 'France', value: 'France' },
  { code: 'GF', name: 'French Guiana', value: 'French Guiana' },
  { code: 'PF', name: 'French Polynesia', value: 'French Polynesia' },
  { code: 'TF', name: 'French Southern Territories', value: 'French Southern Territories' },
  { code: 'GA', name: 'Gabon', value: 'Gabon' },
  { code: 'GM', name: 'Gambia', value: 'Gambia' },
  { code: 'GE', name: 'Georgia', value: 'Georgia' },
  { code: 'DE', name: 'Germany', value: 'Germany' },
  { code: 'GH', name: 'Ghana', value: 'Ghana' },
  { code: 'GI', name: 'Gibraltar', value: 'Gibraltar' },
  { code: 'GR', name: 'Greece', value: 'Greece' },
  { code: 'GL', name: 'Greenland', value: 'Greenland' },
  { code: 'GD', name: 'Grenada', value: 'Grenada' },
  { code: 'GP', name: 'Guadeloupe', value: 'Guadeloupe' },
  { code: 'GU', name: 'Guam', value: 'Guam' },
  { code: 'GT', name: 'Guatemala', value: 'Guatemala' },
  { code: 'GG', name: 'Guernsey', value: 'Guernsey' },
  { code: 'GN', name: 'Guinea', value: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau', value: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana', value: 'Guyana' },
  { code: 'HT', name: 'Haiti', value: 'Haiti' },
  {
    code: 'HM',
    name: 'Heard Island and McDonald Islands',
    value: 'Heard Island and McDonald Islands',
  },
  { code: 'HN', name: 'Honduras', value: 'Honduras' },
  { code: 'HK', name: 'Hong Kong', value: 'Hong Kong' },
  { code: 'HU', name: 'Hungary', value: 'Hungary' },
  { code: 'IS', name: 'Iceland', value: 'Iceland' },
  { code: 'IN', name: 'India', value: 'India' },
  { code: 'ID', name: 'Indonesia', value: 'Indonesia' },
  { code: 'IR', name: 'Iran', value: 'Iran, Islamic Republic of' },
  { code: 'IQ', name: 'Iraq', value: 'Iraq' },
  { code: 'IE', name: 'Ireland', value: 'Ireland' },
  { code: 'IM', name: 'Isle of Man', value: 'Isle of Man' },
  { code: 'IL', name: 'Israel', value: 'Israel' },
  { code: 'IT', name: 'Italy', value: 'Italy' },
  { code: 'JM', name: 'Jamaica', value: 'Jamaica' },
  { code: 'JP', name: 'Japan', value: 'Japan' },
  { code: 'JE', name: 'Jersey', value: 'Jersey' },
  { code: 'JO', name: 'Jordan', value: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan', value: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya', value: 'Kenya' },
  { code: 'KI', name: 'Kiribati', value: 'Kiribati' },
  { code: 'KW', name: 'Kuwait', value: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan', value: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos', value: "Lao People's Democratic Republic" },
  { code: 'LV', name: 'Latvia', value: 'Latvia' },
  { code: 'LB', name: 'Lebanon', value: 'Lebanon' },
  { code: 'LS', name: 'Lesotho', value: 'Lesotho' },
  { code: 'LR', name: 'Liberia', value: 'Liberia' },
  { code: 'LY', name: 'Libya', value: 'Libyan Arab Jamahiriya' },
  { code: 'LI', name: 'Liechtenstein', value: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania', value: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg', value: 'Luxembourg' },
  { code: 'MO', name: 'Macao', value: 'Macao' },
  { code: 'MG', name: 'Madagascar', value: 'Madagascar' },
  { code: 'MW', name: 'Malawi', value: 'Malawi' },
  { code: 'MY', name: 'Malaysia', value: 'Malaysia' },
  { code: 'MV', name: 'Maldives', value: 'Maldives' },
  { code: 'ML', name: 'Mali', value: 'Mali' },
  { code: 'MT', name: 'Malta', value: 'Malta' },
  { code: 'MH', name: 'Marshall Islands', value: 'Marshall Islands' },
  { code: 'MQ', name: 'Martinique', value: 'Martinique' },
  { code: 'MR', name: 'Mauritania', value: 'Mauritania' },
  { code: 'MU', name: 'Mauritius', value: 'Mauritius' },
  { code: 'YT', name: 'Mayotte', value: 'Mayotte' },
  { code: 'MX', name: 'Mexico', value: 'Mexico' },
  { code: 'FM', name: 'Micronesia', value: 'Micronesia, Federated States of' },
  { code: 'MD', name: 'Moldova', value: 'Moldova' },
  { code: 'MC', name: 'Monaco', value: 'Monaco' },
  { code: 'MN', name: 'Mongolia', value: 'Mongolia' },
  { code: 'ME', name: 'Montenegro', value: 'Montenegro' },
  { code: 'MS', name: 'Montserrat', value: 'Montserrat' },
  { code: 'MA', name: 'Morocco', value: 'Morocco' },
  { code: 'MZ', name: 'Mozambique', value: 'Mozambique' },
  { code: 'MM', name: 'Myanmar', value: 'Myanmar' },
  { code: 'NA', name: 'Namibia', value: 'Namibia' },
  { code: 'NR', name: 'Nauru', value: 'Nauru' },
  { code: 'NP', name: 'Nepal', value: 'Nepal' },
  { code: 'NL', name: 'Netherlands', value: 'Netherlands' },
  { code: 'NC', name: 'New Caledonia', value: 'New Caledonia' },
  { code: 'NZ', name: 'New Zealand', value: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua', value: 'Nicaragua' },
  { code: 'NE', name: 'Niger', value: 'Niger' },
  { code: 'NG', name: 'Nigeria', value: 'Nigeria' },
  { code: 'NU', name: 'Niue', value: 'Niue' },
  { code: 'NF', name: 'Norfolk Island', value: 'Norfolk Island' },
  { code: 'KP', name: 'North Korea', value: "Korea, Democratic People's Republic of" },
  { code: 'MK', name: 'North Macedonia', value: 'Macedonia' },
  { code: 'MP', name: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
  { code: 'NO', name: 'Norway', value: 'Norway' },
  { code: 'OM', name: 'Oman', value: 'Oman' },
  { code: 'PK', name: 'Pakistan', value: 'Pakistan' },
  { code: 'PW', name: 'Palau', value: 'Palau' },
  { code: 'PS', name: 'Palestine', value: 'Palestinian Territory, Occupied' },
  { code: 'PA', name: 'Panama', value: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea', value: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay', value: 'Paraguay' },
  { code: 'PE', name: 'Peru', value: 'Peru' },
  { code: 'PH', name: 'Philippines', value: 'Philippines' },
  { code: 'PN', name: 'Pitcairn', value: 'Pitcairn' },
  { code: 'PL', name: 'Poland', value: 'Poland' },
  { code: 'PT', name: 'Portugal', value: 'Portugal' },
  { code: 'PR', name: 'Puerto Rico', value: 'Puerto Rico' },
  { code: 'QA', name: 'Qatar', value: 'Qatar' },
  { code: 'RO', name: 'Romania', value: 'Romania' },
  { code: 'RU', name: 'Russian Federation', value: 'Russian Federation' },
  { code: 'RW', name: 'Rwanda', value: 'Rwanda' },
  { code: 'RE', name: 'Réunion', value: 'Reunion' },
  { code: 'BL', name: 'Saint Barthélemy', value: 'Saint Barthélemy' },
  { code: 'SH', name: 'Saint Helena', value: 'Saint Helena' },
  { code: 'KN', name: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia', value: 'Saint Lucia' },
  { code: 'MF', name: 'Saint Martin', value: 'Saint Martin (French part)' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', value: 'Saint Pierre and Miquelon' },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
  },
  { code: 'WS', name: 'Samoa', value: 'Samoa' },
  { code: 'SM', name: 'San Marino', value: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia', value: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal', value: 'Senegal' },
  { code: 'RS', name: 'Serbia', value: 'Serbia' },
  { code: 'SC', name: 'Seychelles', value: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone', value: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore', value: 'Singapore' },
  { code: 'SX', name: 'Sint Maarten', value: 'Sint Maarten' },
  { code: 'SK', name: 'Slovakia', value: 'Slovakia' },
  { code: 'SI', name: 'Slovenia', value: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands', value: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia', value: 'Somalia' },
  { code: 'ZA', name: 'South Africa', value: 'South Africa' },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
  },
  { code: 'KR', name: 'South Korea', value: 'Korea, Republic of' },
  { code: 'SS', name: 'South Sudan', value: 'South Sudan' },
  { code: 'ES', name: 'Spain', value: 'Spain' },
  { code: 'LK', name: 'Sri Lanka', value: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan', value: 'Sudan' },
  { code: 'SR', name: 'Suriname', value: 'Suriname' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', value: 'Svalbard and Jan Mayen' },
  { code: 'SE', name: 'Sweden', value: 'Sweden' },
  { code: 'CH', name: 'Switzerland', value: 'Switzerland' },
  { code: 'SY', name: 'Syria', value: 'Syrian Arab Republic' },
  { code: 'TW', name: 'Taiwan', value: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan', value: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania', value: 'Tanzania, United Republic of' },
  { code: 'TH', name: 'Thailand', value: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste', value: 'Timor-Leste' },
  { code: 'TG', name: 'Togo', value: 'Togo' },
  { code: 'TK', name: 'Tokelau', value: 'Tokelau' },
  { code: 'TO', name: 'Tonga', value: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia', value: 'Tunisia' },
  { code: 'TM', name: 'Turkmenistan', value: 'Turkmenistan' },
  { code: 'TC', name: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands' },
  { code: 'TV', name: 'Tuvalu', value: 'Tuvalu' },
  { code: 'TR', name: 'Türkiye', value: 'Turkey' },
  { code: 'VI', name: 'U.S. Virgin Islands', value: 'Virgin Islands, U.S.' },
  { code: 'UG', name: 'Uganda', value: 'Uganda' },
  { code: 'UA', name: 'Ukraine', value: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates', value: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom', value: 'United Kingdom' },
  { code: 'US', name: 'United States', value: 'United States' },
  {
    code: 'UM',
    name: 'United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
  },
  { code: 'UY', name: 'Uruguay', value: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan', value: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu', value: 'Vanuatu' },
  { code: 'VA', name: 'Vatican City', value: 'Holy See (Vatican City State)' },
  { code: 'VE', name: 'Venezuela', value: 'Venezuela' },
  { code: 'VN', name: 'Vietnam', value: 'Viet Nam' },
  { code: 'WF', name: 'Wallis and Futuna', value: 'Wallis and Futuna' },
  { code: 'EH', name: 'Western Sahara', value: 'Western Sahara' },
  { code: 'YE', name: 'Yemen', value: 'Yemen' },
  { code: 'ZM', name: 'Zambia', value: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe', value: 'Zimbabwe' },
  { code: 'AX', name: 'Åland Islands', value: 'Åland Islands' },
]
