<template>
  <div>
    <!-- Off, one click turns it on and puts the pairing code straight up.
     - On, it opens that code again rather than switching the feature off:
     - the dialog closes itself the moment a phone connects (see the
     - dialog's own comment), and without a way back to it the only route
     - to a second phone was off-and-on again, which mints a new code and
     - locks out the phone already paired. Switching it off moved into the
     - dialog for that reason - it is the rarer of the two things to want,
     - and the one worth being deliberate about.
     -
     - The badge counts the phones on the line, the same way ConnectButton
     - counts cast targets: this button is otherwise the only place the
     - feature is visible at all, and "is anything actually connected?" had
     - no answer anywhere in the app. -->
    <v-badge
      :model-value="remoteControlStore.phoneCount > 0"
      :content="remoteControlStore.phoneCount"
      color="primary"
    >
      <v-btn
        icon="mdi-cellphone-wireless"
        :color="remoteControlStore.enabled ? 'primary' : undefined"
        :loading="busy"
        :disabled="busy"
        variant="text"
        density="comfortable"
        :title="$t('remoteControl.title')"
        @click="onClick"
      />
    </v-badge>
    <remote-control-pairing-dialog v-model="showPairingDialog" />
  </div>
</template>

<script lang="ts">
import { useRemoteControlStore } from '@/stores/remoteControl'
import RemoteControlPairingDialog from './RemoteControlPairingDialog.vue'

export default {
  name: 'RemoteControlButton',
  components: { RemoteControlPairingDialog },
  data() {
    return {
      busy: false,
      showPairingDialog: false,
    }
  },
  computed: {
    remoteControlStore() {
      return useRemoteControlStore()
    },
  },
  methods: {
    async onClick() {
      // Already on: just show the code again. Nothing is regenerated by
      // opening it, so the phone already paired stays paired.
      if (this.remoteControlStore.enabled) {
        this.showPairingDialog = true
        return
      }
      this.busy = true
      try {
        await this.remoteControlStore.enable()
        this.showPairingDialog = true
      } catch (error) {
        this.$emitter.emit('toast', {
          level: 'error',
          title: this.$t('remoteControl.title'),
          message: this.$t('remoteControl.enableFailed'),
        })
        console.error('[player-bar] Failed to turn remote control on:', error)
      } finally {
        this.busy = false
      }
    },
  },
}
</script>
