name: Publish Windows (Manual)

on: workflow_dispatch

jobs:
    ensure-release:
        permissions:
            contents: write
        uses: ./.github/workflows/_ensure-release.yml

    publish-electron:
        needs: ensure-release
        permissions:
            contents: write
        uses: ./.github/workflows/_publish-electron.yml
        with:
            matrix: |
                [
                  {"os": "windows-latest", "script": "publish:win"}
                ]
